---
repos:
- repo: https://github.com/asottile/add-trailing-comma.git
  rev: v3.1.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/PyCQA/isort.git
  rev: 5.12.0
  hooks:
  - id: isort
    args:
    - --honor-noqa

- repo: https://github.com/Lucas-C/pre-commit-hooks.git
  rev: v1.5.4
  hooks:
  - id: remove-tabs

- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.5.0
  hooks:
  # Side-effects:
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
  # Non-modifying checks:
  - id: name-tests-test
    files: >-
      ^tests/[^_].*\.py$
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-json
  - id: check-symlinks
  - id: check-yaml
  - id: detect-private-key
  # Heavy checks:
  - id: check-ast
  - id: debug-statements
    language_version: python3

- repo: https://github.com/Lucas-C/pre-commit-hooks-markup.git
  rev: v1.0.1
  hooks:
  - id: rst-linter
    files: >-
      ^README\.rst$

- repo: https://github.com/pycqa/pydocstyle.git
  rev: 6.3.0
  hooks:
  - id: pydocstyle

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.32.0
  hooks:
  - id: yamllint
    files: \.(yaml|yml)$
    types:
    - file
    - yaml
    args:
    - --strict

- repo: https://github.com/PyCQA/flake8.git
  rev: 6.1.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-2020>=1.6.0
    - flake8-docstrings >= 1.5.0
    - flake8-pytest-style>=1.0.0
    # - wemake-python-styleguide
    language_version: python3

- repo: local
  hooks:
  - id: pylint
    language: system
    name: PyLint
    files: \.py$
    entry: python -m pylint
    args: []
    stages:
    - manual
...
